// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcgyDliPOuipPU-F8BKVR2DxstoiXHUYM',
    appId: '1:229817064232:web:2825d410a5fd88432b4e1d',
    messagingSenderId: '229817064232',
    projectId: 'edu-vista-ada00',
    authDomain: 'edu-vista-ada00.firebaseapp.com',
    storageBucket: 'edu-vista-ada00.appspot.com',
    measurementId: 'G-XJ29LM4MNQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPdDk-sZo_0pKNmzump17FsO5m9cSABlM',
    appId: '1:229817064232:android:ac11a625c93ae8792b4e1d',
    messagingSenderId: '229817064232',
    projectId: 'edu-vista-ada00',
    storageBucket: 'edu-vista-ada00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlQLA9NlJprJoi0-KUjJJPUoZyYyJIIiM',
    appId: '1:229817064232:ios:0160ebc1f95bd3cf2b4e1d',
    messagingSenderId: '229817064232',
    projectId: 'edu-vista-ada00',
    storageBucket: 'edu-vista-ada00.appspot.com',
    iosClientId: '229817064232-kvr2mdfd0uln05d88s2ouhk69tqc69es.apps.googleusercontent.com',
    iosBundleId: 'com.example.task6Adv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlQLA9NlJprJoi0-KUjJJPUoZyYyJIIiM',
    appId: '1:229817064232:ios:0160ebc1f95bd3cf2b4e1d',
    messagingSenderId: '229817064232',
    projectId: 'edu-vista-ada00',
    storageBucket: 'edu-vista-ada00.appspot.com',
    iosClientId: '229817064232-kvr2mdfd0uln05d88s2ouhk69tqc69es.apps.googleusercontent.com',
    iosBundleId: 'com.example.task6Adv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcgyDliPOuipPU-F8BKVR2DxstoiXHUYM',
    appId: '1:229817064232:web:fee7171277c641012b4e1d',
    messagingSenderId: '229817064232',
    projectId: 'edu-vista-ada00',
    authDomain: 'edu-vista-ada00.firebaseapp.com',
    storageBucket: 'edu-vista-ada00.appspot.com',
    measurementId: 'G-GC5MJFHY6D',
  );

}